### ISSUE TITLE
Just holding down left mouse button without dragging

### ISSUE THREAD

**Issue by Inzaniity** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#1]
When holding down the left mouse button without having a file that gets dragged, the behavior is the same as when dragging a file. 

Would be nice to have a check whether a file is being dragged or not. 

I know this is an edge case, but a case nonetheless!

**Comment by HerMajestyDrMona** [comment]
Thanks for your comment.

Do you have some idea how to achieve it? I was thinking about checking for the cursor icon change, but it seems to be the same arrow when dragging files.

Maybe for now it would be enough to detect if the left mouse button wasn't clicked while in the taskbar area to minimize risk of fix activation when moving taskbar icons?

**Comment by wjk** [comment]
> It would require sniffing messages for the Windows Explorer or other dirty things.

Actually, no it doesn’t. It is entirely possible to tell if there is a file being dragged by examining the [OLE clipboard data object](https://docs.microsoft.com/en-us/windows/win32/shell/dataobject) to see if it contains any of [these data types](https://docs.microsoft.com/en-us/windows/win32/shell/datascenarios#general-guidelines). This is how the shell tells the drop target what is being dragged. Any process can read from or write to the data object, so you are not depending on any private or undocumented behavior here. If none of the data types at the second link above are currently present on the data object while processing a potential drop, you can be quite certain that no file is being dragged. Hope this helps!

**Comment by HerMajestyDrMona** [comment]
Thanks @wjk! It's very helpful. I'll try it today at night.

**Comment by rareboi** [comment]
Great app. Finally DragAndDrop works. The latest update is very encouraging. And if your program does not start automatically when Windows boots, just run the "shell: startup" command and add a shortcut to the folder.

**Comment by HerMajestyDrMona** [comment]
@rareboi Thanks for your feedback. Using `shell: startup` is pointless, as the program can be [configured](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md) to autostart. It's enough to click the "Configure..." button from the program tray icon menu and save the file. 

Autostart was disabled by default in [version 1.4.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-1400----2021-10-21-1300-cet), because many antivirus programs found it as a "malicious" behaviour. Especially because users started the program directly from the "Downloads" folder, without copying it to a different location.

Here are the source code lines for the Autostart function: [Windows11DragAndDropToTaskbarFix.cpp#L1107](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/c6fa46159cbf97ec994bb63ef5a293b65e09a7c2/Windows11DragAndDropToTaskbarFix/Windows11DragAndDropToTaskbarFix.cpp#L1107)

It uses the `Software\\Microsoft\\Windows\\CurrentVersion\\Run` registry path, so it should work just fine. If it doesn't then it might be needed to start the program as administrator 1 time, so it can write to the registry (but for me it never was needed).

**Comment by HerMajestyDrMona** [comment]
@Inzaniity  @Gregoryweix  @wjk

This issue should now be fixed in [version 2.0.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2000----2021-11-28-1530-cet) :)

Please let me know if everything works fine on your computers.

**Comment by Inzaniity** [comment]
> @Inzaniity @Gregoryweix @wjk
> 
> This issue should now be fixed in [version 2.0.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2000----2021-11-28-1530-cet) :)
> 
> Please let me know if everything works fine on your computers.

Haven't had the time yet to test it, will report back once I did!

**Comment by paddino** [comment]
I've tried version 2.0.0.0 and it seems to work fine. The issue seems to have been solved.

**Comment by HerMajestyDrMona** [comment]
Thanks for the confirmation. I guess we can close this issue now.
