### ISSUE TITLE
Feature of Hide Tray Icon & Tray Icon Customization

### ISSUE THREAD

**Issue by Xnor-bear** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#15]
It performs well on my PC, nice work! 😜
The tray icon is wonderful, but a little out of style.
So what I wanna say is could you add the feature of hiding tray icon or customization,etc.

I checked the documentation of configuration and found nothing.

![image](https://user-images.githubusercontent.com/54651817/139679153-11062798-cb3b-4ed2-9ad0-b70bd26818dd.png)

Thank you.

**Comment by HerMajestyDrMona** [comment]
Hi @Xnor-bear. If you have a possibility to compile the program yourself, you could simply replace `Windows11DragAndDropToTaskbarFix.ico` with something else.

I will add an option to disable the Tray Icon in the next version.
I didn't add it yet, because the window that is created together with the tray icon is used to fix a bug after the "Sleep Mode" (more details in the Changelog). Then a small program window appears for 100 milliseconds in order to force the taskbar `RECT` reload by Windows. So I didn't have much time to test if showing that "fix" window would work without the tray icon.

**Comment by Xnor-bear** [comment]
Got it 👌
I will check out changelog carefully.
Thank you 😊.

**Comment by HerMajestyDrMona** [comment]
Hi @Xnor-bear. This option has been added in [version 1.8.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-1800----2021-11-02-0700-cet)

Have a nice day.
