### ISSUE TITLE
Something Annoying I Hope To Fix

### ISSUE THREAD

**Issue by Alwasmi69** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#28]
Hi, 

I'm facing a problem when I'm selecting a long text and the mouse reach the bottom of the screen like for example I want to select text on word and I have more than one page, then when I select this text and I want to select specific pages using the cursor and the cursor reach the most bottom of the screen and there are some apps open then it switches to the app where the cursor reaches in the taskbar and my work (selecting the text) will be canceled.

This is a video to explain more:
https://user-images.githubusercontent.com/95059797/143514003-fd948b37-cd6a-4fb1-8d70-5701f34d640f.mp4

Thank you.

**Comment by HerMajestyDrMona** [comment]
Looks like the same problem aa described in the open issue here: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/1

I currently have no idea how to add a detection of it. I tried many possibilities already.

**Comment by HerMajestyDrMona** [comment]
@Alwasmi69, this issue is partially fixed in [ver. 1.9.2.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/releases) could you please check how it works now?
Partially, because it ignores the drag event when the mouse cursor icon was I-beam (when pressed the mouse button). Sometimes, when selecting text in Word the icon is still normal arrow, so it can not be detected, but in most cases it should solve this problem.

**Comment by 4rtz1z** [comment]
This fix really bring text selecting a great improvement, could you also apply this on Excel when the "+" cursor is being dragged to bottom screen for faster scrolling

**Comment by HerMajestyDrMona** [comment]
Please check now in ver. 1.9.2.1.

**Comment by 4rtz1z** [comment]
Sure, let me report after the test

**Comment by HerMajestyDrMona** [comment]
Opps, something is wrong. I deleted that release. Not sure how it worked fine... Maybe I tested with the program shut down...

**Comment by HerMajestyDrMona** [comment]
Oh nooo... This icon seem to be excel-special, and the ID of it changes every time a new document is open :/

**Comment by 4rtz1z** [comment]
what a bummer, any chance to disable it on excel ?

**Comment by HerMajestyDrMona** [comment]
Unfortunately I don't know :(

The solution would be getting EXCEL.EXE location from system registry, then reading that file resources for Cursor icons, then each time the mouse button is clicked comparing the current cursor icon with the one from EXCEL.EXE resources... I think it would need to be done pixel-by-pixel. I think it's too complicated for this fix...

Alternatively, we could make a list of ignored programs (manually configured), but then even text / dragging from Word/Excel wouldn't work.

Or maybe some "ignored zone" on the taskbar. So dropping files would start the program behaviour only if dropped 5-10px from under the top of the taskbar. But that would also get frequently miss-clicked..

**Comment by 4rtz1z** [comment]
How about only detect drag and drop when only on "normal select" cursor ? doesn't it always a normal select cursor when doing drag and drop ? cmiiw

**Comment by HerMajestyDrMona** [comment]
I was thinking about it, but it depends on programs. It's hard to predict what programs people use. For example when dragging selected text from Word Office, the icon is different than the normal arrow. Someone might use some "alien" program for 3D graphics, and dragging items might change cursor to something totally different (like the + excel icon). So I find it as a wrong solution that would make people think that the program "doesn't work".

I wish it was possible to detect for the "incorrect" image under the mouse when dropped on Windows 11 taskbar. I tried to detect it before, but couldn't find a solution (no new window is changing visibility status / is created when it happens).

**Comment by 4rtz1z** [comment]
Maybe add that as an option to enable and disable might be great ? (For average user/office people that mostly use only explorer to drag and drop to another windows)

**Comment by Alwasmi69** [comment]
@HerMajestyDrMona actually solves the issue in word, but still, there are so many different apps not fixed but I loved your tool anyway and I will still use it. 
I really appreciate fixing the word issue and I wish to improve this tool to become better in the future.

I want to help but I'm still studying the languages and the concepts of programming :) 
I have a suggestion, if you can search inside windows 10 files to see how they did it in windows 10 might this help you to avoid our problem.

Thank you

**Comment by HerMajestyDrMona** [comment]
> I have a suggestion, if you can search inside windows 10 files to see how they did it in windows 10 might this help you to avoid our problem.

I'm not sure how that would help. This program uses a totally different workaround with "guessing" what user is currently doing and which icon on the taskbar is hovered. There is nothing from older versions of Windows used in this workaround program.
But I believe it looks this way, because it's currently working almost flawlessly :)

> Maybe add that as an option to enable and disable might be great ? (For average user/office people that mostly use only explorer to drag and drop to another windows)

I'm not convinced to this method, when I know that the cursor might differ from the arrow one in many cases. Since this is an open source program, the best solution would be if you could compile the program yourself for your own needs. You would need to edit function `IsCursorIconAllowed()` to the following:

```
bool IsCursorIconAllowed() {
	CURSORINFO cursorInfo = { 0 };
	cursorInfo.cbSize = sizeof(cursorInfo);
	if (::GetCursorInfo(&cursorInfo))
	{
		std::wcout << L"Cursor Info: " << cursorInfo.hCursor << endl;
                HCURSOR hCursorArrow = LoadCursor(NULL, IDC_ARROW);
                if (cursorInfo.hCursor == hCursorBeam) {
                       return true;
                }
		/*HCURSOR hCursorBeam = LoadCursor(NULL, IDC_IBEAM);
		if (cursorInfo.hCursor == hCursorBeam) {
			return false;
		}*/
		//Excel + icon:
		/*if (cursorInfo.hCursor == (HCURSOR)0xB09CB) {
			return false;
		}*/
	}
	//return true;
       return false;
}
```

This way it would only work if the cursor was a normal arrow, and nothing else.

**Comment by HerMajestyDrMona** [comment]
Seems like I did it!

@Alwasmi69 @4rtz1z 
Would you guys like to test this feature before I release it as ver. 1.10.0.0?

Generally, I managed to test the colors of pixels above the mouse:
15 pixels above the mouse cursor on the taskbar: RGB 242 242 242 #F2F2F2
21 pixels above the mouse cursor on the taskbar: RGB 255 0 0 #FF0000

This way, when file / text is being dragged and hovered over the taskbar, the function returns true because finds the correct white and red colors at certain positions above the mouse.

It still needs to be tested how it behaves with different DPI scaling settings, but I believe it's the right thing to do :)

**Comment by 4rtz1z** [comment]
@HerMajestyDrMona thankyou for keep improving and fixing this issue. yes, i’ll gladly try it and report it back

**Comment by Alwasmi69** [comment]
@HerMajestyDrMona you are amazing! Thank you very much for all your work and I will support you.
I would to try and give you my feedback when I get free time.
Thanks again for this opportunity and I'm glad to be part of this with both of you @HerMajestyDrMona @4rtz1z :)

**Comment by HerMajestyDrMona** [comment]
Thanks! I'll upload the file when it's done.

As I thought,, the different DPI scaling causes problems, so I'm now working to detect the DPI scaling (this is done) and optimizing the code, so it won't update DPI scaling too often. I need to do it slowly, because the program supports multiple monitors which can have different scaling settings, so I don't want to make a mistake there.

**Comment by HerMajestyDrMona** [comment]
@4rtz1z  @Alwasmi69 

Here it is:
https://we.tl/t-p9VPsWcKj8

Sorry, I couldn't upload .exe format in the GitHub comment, but I hope it's fine.

Please let me know how it works on your computers :) If possible, please also set different DPI scaling settings (in Settings on Windows 11) to see if everything is working as expected.

I wonder if the version number should be 1.10.0.0 or simply make it 2.0.0.0... Hmmm...

**Comment by HerMajestyDrMona** [comment]
@4rtz1z @Alwasmi69 

This issue should now be fixed in [version 2.0.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2000----2021-11-28-1530-cet) :)

Please let me know if everything works fine on your computers.

**Comment by 4rtz1z** [comment]
THANKYOUUUUUU !!!!
Now it works awesomeeee, @HerMajestyDrMona CONGRATULATION on fixing this

**Comment by Alwasmi69** [comment]
@HerMajestyDrMona Wow!! it's really nice now and it's working great!
Thank you very much, and btw you are an amazing person :)

**Comment by HerMajestyDrMona** [comment]
Thanks for your good words and confirmation that the fix works :) I guess we can close this issue now.
