### ISSUE TITLE
Windows Defender positive

### ISSUE THREAD

**Issue by morralletti** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#30]
Version 2.0.0.0

![image](https://user-images.githubusercontent.com/40687956/143787456-c7855fcf-7b8a-40ca-beeb-094a1f17cf5a.png)

**Comment by HerMajestyDrMona** [comment]
I don't get this detection, but I don't understand what I'm supposed to do with "issues" of this type? Maybe it should be posted to Microsoft Defender team instead of me.

The story is always the same, Windows Defender detectes new programs as malicious, then I submit a false positive form and they delete it from detections. Do they even verify what they're doing? I assume they simply detect everything new and unsigned as malicious without any reasons nor algorithms triggered.

**Comment by HerMajestyDrMona** [comment]
![Screenshot 2021-11-29 061403](https://user-images.githubusercontent.com/24290461/143812662-948227a2-33da-4f4c-b7f5-fdca608f09f4.png)
