### ISSUE TITLE
Issues with maximizing/minimizing windows

### ISSUE THREAD

**Issue by Gigafrost** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#36]
Hello, I love this tool, but sometimes I've noticed that the windows randomly "lock" while using it.
As in. After dragging and dropping something, the window sometimes prevents me from switching between different windows in the task bar. It will simply blink or flash without doing anything.

 The only one I've found was closing the program, which fixed the issue. Any workarounds for this? Thanks!

**Comment by HerMajestyDrMona** [comment]
Hi. I'm not sure if I understand the problem fully.

You're dragging some file to the taskbar icon, then it restores the minimized window and what happens then? You are unable to switch to other programs using ALT+TAB, or you're unable to switch to the other programs by clicking their icons on the taskbar?

**Comment by Gigafrost** [comment]
Thanks for the quick response, and yes I am unable to switch to other programs by clicking on the icon. Alt + TAB works fine however.

It's hard to replicate the issue since it happens randomly, but I believe it has to do with programs that take a while to load, such as booting up an adobe program or updating windows / my graphics card. Of course though as I type this, I have it running right now and it's working fine, so I think it's more of a minor bug than a big issue.

Also I haven't used any taskbar size mods in the registry, no.

**Comment by HerMajestyDrMona** [comment]
Unfortunately I was not able to reproduce this issue.

Generally, it sounds very unlikely that this program would "freeze" the window / taskbar. It simply uses the Win+T hotkey, then Arrows / ENTER keys in order to maximize windows. So there is nothing that would make the program wait for the timeout.

What exactly do you mean by: "It will simply blink or flash"? Does it show the Orange flash on the icon (like there was a new notification, etc.) or do you mean this white frame that signals which icon is currently selected by the program?

For me it sounds like the system ignores the mouse-left-key-up signal, and treats it like the mouse button is all the time pressed. Really strange.

**Comment by Gigafrost** [comment]
> Unfortunately I was not able to reproduce this issue.
> 
> Generally, it sounds very unlikely that this program would "freeze" the window / taskbar. It simply uses the Win+T hotkey, then Arrows / ENTER keys in order to maximize windows. So there is nothing that would make the program wait for the timeout.
> 

That's what I thought too. Thanks for clearing that up!

> What exactly do you mean by: "It will simply blink or flash"? Does it show the Orange flash on the icon (like there was a new notification, etc.) or do you mean this white frame that signals which icon is currently selected by the program?
> 
> For me it sounds like the system ignores the mouse-left-key-up signal, and treats it like the mouse button is all the time pressed. Really strange.

The app icon would flash orange, like a notification, except when you click on it it doesn't respond to the click for some reason.

And yeah that's exactly the behavior I was experiencing! Like it would act as if the right mouse button was pressed down. I noticed that this behavior was a bit more "extreme" when I had an older version of this program installed. As in, it would behave like I was able to just move my mouse to the bottom right edge of the screen and it would show the desktop (instead of needing to click the corner to show desktop). 

Note: That desktop stuff was an issue that doesn't seem to appear anymore, so I think that's been resolved already in the latest patch. This also only happened for a split second, unlike the flashing app notification thing which acted that way until I restarted the draganddrop taskbar app. However it doesn't seem to do it anymore now, so I have no idea what "triggers" this behavior.

**Comment by HerMajestyDrMona** [comment]
Thanks for detailed clarifications!

Let's observe it for some days and see if something similar happens.

The only thing that I can come up with is that when system load is high, it ignores the `Low Level Mouse Hook` thread in this program, therefore the program still thinks that the mouse button is pressed (?). That would be very strange as I thought it should work 100% of the time. Maybe I could add an extra check if the mouse button is currently pressed in the program loop to make sure that it's really pressed.

So in summary: I think when the system CPU usage is 100%, then the `Low Level Mouse Hook` thread timeouts (otherwise windows would get mouse movements blocked / the cursor wouldn't move on screen). It should be possible to test while performing some CPU benchmark maybe, and then dragging files. I'll see if I can test it myself. If it happens to you again, please let me know, and I'll just ask these extra mouse key status checks and send you a file to test. When it's confirmed to fix the problem it can go to the main version :)

**Comment by Gigafrost** [comment]
Sounds good! I had a hunch that it had something to do with memory usage. 
I'll definately let you know if it acts up again, but at least it's behaving really good right now!

**Comment by HerMajestyDrMona** [comment]
Hi @Gigafrost 

I added an additional detection of the left/right mouse button state in [ver. 2.1.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2100----2021-12-13-1600-cet).

Hopefully it will fix these issues forever, although I could not reproduce this problem anymore on ver. 2.0.0.0. Either way, an additional mouse state detection won't hurt :)

Greetings.

**Comment by Gigafrost** [comment]
I recently updated and it's working great! Thanks so much!
