### ISSUE TITLE
Support for second monitor

### ISSUE THREAD

**Issue by quiquejbb** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#60]
If the target folder / window is in a second monitor, the drop functionality does not activate the window. Is it possible to support secondary monitors?

**Comment by HerMajestyDrMona** [comment]
The support for multiple screens is already in the program since: this version: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-1500----2021-10-27-1500-cet

Could you please describe step by step what is happening?

**Comment by HerMajestyDrMona** [comment]
Hi again.

I added some improvement for the multi-monitors in ver. [ver. 2.3.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CHANGELOG.md#ver-2300----2022-02-15-1730-cet).

Please let me know if it solves your problem, or provide more information about it, so I can try to reproduce it step-by-step.

**Comment by TheLegendOfXela** [comment]
I have two monitors, my main being 4k, and my second monitor being 1080p. When trying to drag a file into the bottom right of my 4k monitor (to go to the desktop), it doesn't work.

**Comment by HerMajestyDrMona** [comment]
@TheLegendOfXela The "Show desktop" button (bottom right of the taskbar) is only present on the primary monitor. You can see it by trying to click on that area on the second monitor. It will not minimize running programs when clicking there. From what I remember the same behaviour was on Windows 10. Since the "Show destop" window is missing on the other screens, it would complicate the program's work (impossible to determine if the mouse is really hovered over that area, full screen-programs would minimize, etc.). So the safest way is to leave it as it is, especially when it matches the old drag-and-drop behaviour.

**Comment by TheLegendOfXela** [comment]
Hi! I am talking about my primary monitor. Dragging to the corner to bring up the desktop isn’t working. I only specified resolution because it may be because both screens are running different resolutions.

**Comment by ODINru** [comment]
yes

пн, 9 мая 2022 г. в 22:08, Dr.MonaLisa ***@***.***>:
