### ISSUE TITLE
Randomly a Window popping up.

### ISSUE THREAD

**Issue by biswasmoheshwar** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#62]
Randomly a Window popping up called Windows11DragAndDropToTaskbarFix. also, a taskbar icon. like in issue #45. It's happening too fast so I can't take a screenshot. Fix it, it's so annoying.

**Comment by HerMajestyDrMona** [comment]
Fix what? If you read the previous issue, this window is popping up intentionally in order to fix another Windows 11 bug that sends incorrect taskbar window rect and disallows the program from functioning normally. If you don't need this fix you can read the configuration to learn how to disable this behaviour and be "less annoyed".
