### ISSUE TITLE
The Code is not maintainable

### ISSUE THREAD

**Issue by ycsvenom** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#75]
if you have another version of the code that is well-splited into smaller pieces of code please upload it instead of this pile of code
NO OFFENSE

**Comment by HerMajestyDrMona** [comment]
You're writing "NO OFFENSE", but your question makes a total nonsense, suggesting that I am hiding a different version of the code and that I am sharing some garbage public. There's clearly no other intention in creating an "issue" like this, other than to sound offensive, or simply inform people around about your low self-esteem.

Windows11DragAndDropToTaskbarFix was coded in quite a short time, and yet it's a pretty advanced software that takes care of almost all potential problems during the usage. If it's easier and faster for me to work on 2 files, then it's what I'm doing.

You're welcome to rewrite everything into "well-splited smaller pieces" and share as your own repository. However, it's surprising if you think it's worth the effort for a "fix" that will not longer be needed just in few months from now.

I don't want to sound offensive as well, but I can't stand people that are caring about the code visuals more than the actual work of the software. After all, binaries even look the same after compilation. And even then, looking at the current code, it's not that unclear. It's actually easier to analyze things when it's not needed to jump between different files. 

So no, there won't be a code rewriting for a program that won't be used in the near future, and that is already pretty stable and effective.

**Comment by ycsvenom** [comment]
Look
I am really sorry if I sounded offensive but what you said is not actually true. 
I red your variables and function naming and its pretty good and well written. 
So I told myself that he knows how clean code, so I thought that you mixed all files in some big files so the software becomes faster, nothing more. 
I am really sorry again if I sounded offensive and I really liked your work.

**Comment by HerMajestyDrMona** [comment]
Oh well... I think I overreacted a bit since it was late and I was tired, so I also apologize that I sounded rude in my reply.

I'm glad that you like the variable and function names :) But it's actually one of the most criticized thing that I hear from people looking at my codes :) Most of people claim that variable names should be shorter, and for me all these tips make no real difference, because as result, we always get the same output binary. Same with the number of files: splitting the code to many files won't make the software run faster. The compilation process might be a tiny bit faster, but execution identical. W11DADTTF already uses multiple threads to offload the work, and not to slow down the LowLevelMouseProc thing, which in worst cases could result in mouse lags.

Regarding the non-maintainable code, I posted a few details regarding it in the change log:

[[ver. 1.1.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarPartialFix/releases/tag/v1.1-release)] - 2021-10-15, 04:55 CET
> - Please note that the source code now contains a lot of unused functions. It's because I'm still working on a workaround that would prevent opening programs if their main window can't be found. What I've done now is:
> [...]
> - Please note that the source code will be cleaned when there are less serious things to focus on.

[[ver. 1.2.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/releases/tag/v1.2.0.0-release)] - 2021-10-18, 13:25 CET
> - Traditionally, the code contains a lot of new, unused functions from my tests. Before I found the Win+T method, I created some complicated stuff to simulate mouse cursor clicks and switching between windows. It can be vieved under function Experimental_Workaround_for_buttons_Eleven_Plus().

[[ver. 1.7.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/releases/tag/v.1.7.0.0-release)] - 2021-10-31, 17:10 CET
> - The source code still looks awful, sometimes the configuration variable names still make no sense. All this might be improved in the future, but I prefer to focus on important things, especially when we won't need this fix in 1 year (Windows 11 22H2 release).

[[ver. 1.9.0.0](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/releases/tag/v.1.9.0.0-release)] - 2021-11-15, 06:00 CET
> - Source code: added file Windows11DragAndDropToTaskbarFix.h. Moved variables and function definitions to it.


So yes, I was planning to clean it a bit when it's 100% stable, but then there were news about the drag and drop returning to Windows 11, etc. That's why I continued improvements and fixes on the existing code. Then, looking at it now, it wouldn't be an easy task to clean it up. There were so many circumstances that were used in the code to workaround bugs and predict the drag-and-drop events, that there were many possible things to break while rewriting it. And then it would be needed to test all things again. For me it would be a waste of time, when the program already works and does what it's supposed to do. I hope that explains why it's the way it is :)

**Comment by ycsvenom** [comment]
Thanks 
i know c++ well (from Functional to Object Oriented and i wrote many many code in it), but i don't know how to start playing with OS.
can you point a good resource where i can start learning that thing?

**Comment by HerMajestyDrMona** [comment]
> Thanks i know c++ well (from Functional to Object Oriented and i wrote many many code in it), but i don't know how to start playing with OS. can you point a good resource where i can start learning that thing?

I never read any tutorial / book for it. Just googed up what I need and learnt this way. I had a goal (fixing an old game problems on Windows), so I suppose this helped a lot.

**Comment by ODINru** [comment]
Hi, everything is fine, I just wanted to try to optimize your excellent
code and change the icon of the application itself, I am shocked by your
knowledge, you are well done :)
I wish you further large and cool projects, sincerely, Odin and Green Box
GameDev.😊👍

сб, 30 апр. 2022 г. в 23:18, ycsvenom ***@***.***>:
