### ISSUE TITLE
Can not remove complete from computer. Worried its malware or spyware 

### ISSUE THREAD

**Issue by lumacski** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#82]
Hi there I was able to remove the file and delete it but whenever I go to my startup applications settings I still see it there and I cannot remove or grey out the button to have it not start up automatically, I cant uninstall in through the add or remove program  section and I cant  find any  trace of the file through my search tool.
![Screenshot 2022-07-24 013103](https://user-images.githubusercontent.com/109870275/180616328-c39395ed-60c7-4ff9-998d-9073fa5f9994.png)

**Comment by lumacski** [comment]
sorry am not very tech savy when I clicked the file my screen just refreshed and nothing happened so its worrying me

**Comment by HerMajestyDrMona** [comment]
Hi. As described here: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/issues/81#issuecomment-1180696244


> It's a good question actually.
> 
> All you will need to do is quit the program, and then delete (or rename) the .exe file.
> 
> It's not required, but you can also remove the Autostart key from the system registry.
> 
> As described here: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md#should-the-program-run-automatically-on-system-startup
> 
> Edit file `Windows11DragAndDropToTaskbarFixConfig.txt` and change to:
> 
> ```
> AutomaticallyRunThisProgramOnStartup=0
> ```
> 
> Then restart the program (so it will remove the autostart key automatically), then quit it again, and delete or rename the .exe file: `Windows11DragAndDropToTaskbarFix.exe` or `Windows11DragAndDropToTaskbarFix_Static.exe`.
> 
> If you've already removed the .exe file before disabling autostart, you can simply remove this registry key:
> 
> ```
> HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\Windows11DragAndDropToTaskbarFix
> ```
> 

If you already removed the .exe, then you need to remove the registry key manually. Otherwise just disable autostart by the config file, before removing the exe, so it will clear it automatically.

The most simple method to remove the registry key from Autostart:
- Download the program again, and paste to a different folder (the one where the configuration file "Windows11DragAndDropToTaskbarFixConfig.txt" is not present).
- Start the fix program, and then exit it.
- Remove the program.

This will start the fix with default configuration, which has Autostart disabled. It will remove the existing key from the registry. Then you can normally delete the .exe.

**Comment by lumacski** [comment]
I tried searching for it and downloaded all the files and the one you mentioned was not there :(  this is really alarming  I downloaded every available file this time..

**Comment by HerMajestyDrMona** [comment]
I added the .reg file that allows you to remove the Autostart key in case it's left: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/commit/3e407556858272a3a0f72fa025bd9186d8d906c9.

This .reg file removes `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\Windows11DragAndDropToTaskbarFix`  entry from the system registry. It's only useful if you deleted `Windows11DragAndDropToTaskbarFix` without disabling Autostart in the config file first. Use it when you want to remove the `Windows11DragAndDropToTaskbarFix` entry from Windows 11 `Settings` -> `Apps` -> `Startup`.

You can download it here:
https://downgit.github.io/#/home?url=https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/Remove_Autostart_RegKey_Windows11DragAndDropToTaskbarFix.reg

After that open the .zip file, and open file: `Remove_Autostart_RegKey_Windows11DragAndDropToTaskbarFix.reg`.

![Screenshot 2022-07-24 004343](https://user-images.githubusercontent.com/24290461/180625246-5d3e8d99-366a-4b3e-9519-4a30a7d8c917.png)

**Comment by HerMajestyDrMona** [comment]
> I tried searching for it and downloaded all the files and the one you mentioned was not there :( this is really alarming I downloaded every available file this time..

I'm not sure what you were doing. The main page clearly guides what to do: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#readme

There is a button called: [Download Binary (Windows11DragAndDropToTaskbarFix.exe)](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/releases/)

It redirects to the Releases page where you can download the program the same way as you initially did it.

**I would also appreciate if you stopped insulting me. The low computers knowledge doesn't excuse you from suggesting that I provide malicious software. Your "alarming" claims are especially weird when they're posted on an open source project page.**

Every information about the program behaviour is and was described in [CONFIGURATION](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/blob/main/CONFIGURATION.md). It explains which registry key is created in case user enabled Autostart.

**Comment by lumacski** [comment]
Well i apologize I did not mean to insult you.  Regarding the the file I
only clicked the  multiple folders and it was downloaded to my computer.
Anyways. Again I apologize i have offended you. I was alarmed cause I
realized I downloaded and installed it incorrectly.

**Comment by HerMajestyDrMona** [comment]
@lumacski I think you most likely downloaded the source files. These files are used for people to compile the program themselves. It means that programmers / people who can understand the code are able to read what exactly the program is doing, step-by-step, apply changes and compile (create the .exe file). I provide the already compiled executables on this page: [Download Binary (Windows11DragAndDropToTaskbarFix.exe)](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/releases/) so ordinary users can simply download and run it without extra steps.

The program does not have any extra installer, because it works portably. It does not change system settings or create additional files (with a small exception of a cookie file in the Temp folder for the pixels detection fix). The only exception is the autostart registry key. When you open the program settings, by clicking on the "Configure..." field after clicking on the Megan Fox Mona Lisa icon, you can set option that allows you to start the program automatically on system start. It creates the registry key which I described above.

When you correctly removed the program (by simply deleting the .exe file), the Autostart key was still remaining in the system registry. So, in Settings -> Apps -> Startup you could still see the name of the program.

As I mentioned above, this could be fixed by downloading the program again, starting it 1 time from the folder where the configuration file  `Windows11DragAndDropToTaskbarFixConfig.txt` is not present. This way, the program would delete the autostart key from the registry (because it's set by default to not create this key, and remove if it's present). So this would instantly fix the issue.

If somebody doesn't want to download the program again (for any reasons), then I provided the .reg file that removes the existing autostart key if it exists. It's described here: https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix/commit/3e407556858272a3a0f72fa025bd9186d8d906c9#commitcomment-79304765

I hope it explains why you could still see the program name in Windows 11 Settings. I understand why you could be worried, so I'll try to also explain why GitHub is a different site than the ones you usually find on google when you download other programs:
- On GitHub projects are free and Open Source. It means that you don't need to download pre-compiled executable yourself, but you can verify everything inside the program and then compile it yourself.
- If there was something harmful in the program, it would already be signaled by other users, and probably the project would be removed from GitHub by moderators. This program has over 1300 stars, and probably thousands of downloads, so if something harmful was in it, then for sure somebody would already notice it and take actions to report the project.
- When you download a program from the other non-open-source websites, these programs usually include the "premium" version with additional features. The providers of these websites don't share the source codes, so it's impossible to verify the code and compile yourself. One of the reasons is that somebody would probably steal it and re-compile under other name, using someone's else work to monetize it.
- So that's why when you downloaded the open source project, you are much safer than if you started a random .exe file downloaded from the Internet. Obviously I can not control if somebody else re-compiled this program and uploaded to some other website, but I'm referring to the Releases page of this project.

And don't worry if you sounded offensive. It's understandable, but I also mention these things when I disagree with it. This way you will be more cautious in the future when you'll want to get help on some other project names, etc. So every discussion goes to the positive ending. I only mentioned that it was an "insult" to make you realize these things and avoid the same mistake in the future. I didn't feel offended personally.

**Comment by lumacski** [comment]
Thank you. Sir again i am sorry. I got it to work this time so thank you
very much
