### ISSUE TITLE
Alternative without the need of this program.

### ISSUE THREAD

**Issue by Limoster** [HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#85]
The program does not seem to work for all cases, like dragging an URL from Edge to the file explorer.
I would like to point out to anyone who is frustrated like me that you can ALT+TAB instead of dragging via the taskbar.
While this does not solve the taskbar drag & drop, it does not require you to use this script.
Please inform in the readme that this is a viable solution as a LAST RESORT.

**Comment by HerMajestyDrMona** [comment]
First of all, I just tested dragging an URL from Edge to Windows Explorer on Windows 11 21H2, and it seems to work fine:

![Screenshot 2022-09-26 182739](https://user-images.githubusercontent.com/24290461/192331195-d7ce6281-1432-4610-b21a-6289e9fd8814.png)
![Screenshot 2022-09-26 182845](https://user-images.githubusercontent.com/24290461/192331259-839907a7-e662-44fb-ad9f-714d967e95dc.png)

Therefore your reported issue is invalid and might be caused by your other system modifications, not this program.

As described in [Limitations](https://github.com/HerMajestyDrMona/Windows11DragAndDropToTaskbarFix#limitations), you might need disable the `DetectKnownPixelColorsToPreventAccidentalEvents=0` feature if you experience problems.

Using ALT+TAB is an awful solution for people who have many programs open. It requires wasting time on multiple ALT+TAB key presses when switching to the expected window. People are not fans of this solution.

This is a Windows11DragAndDropToTaskbarFix GitHub page, not a Windows 11 Tutorial with "100 Drag & Drop Alternatives", so I don't see any reason to update the READ ME page with that. People usually find this program as one of the solutions in the other online guides.

The LAST RESORT is updating Windows 11 to version 22H2, where the drag & drop feature was restored natively, so this program or any other workaround is no longer needed.
